package main

var content = `// Code generated by golang-di v1.0.0. DO NOT EDIT.

package services

import (
	"github.com/euskadi31/go-service"
)

func init() {
	{{- range $i, $service := .Services}}
	service.Set("{{$service.Identifier.String}}", func(c service.Container) interface{} {
		{{- range $j, $param := $service.Params}}
		param{{$j}} := c.Get("{{$param.String}}").({{$param.String}})
		{{end -}}

		return {{$service.Identifier.Package}}.{{$service.FactoryName}}(
			{{- range $j, $param := $service.Params}}
			param{{$j}},
			{{end}}
		)
	})
	{{end}}

}

`
